### ISSUE TITLE
Error message for user disliking all photos and we run out of photos

### ISSUE THREAD

**Issue by grlucy** [bferriman/pet-spiration#42]
If the user dislikes every photo (thumbs down button) then we will eventually run out of photos and not be able to move onto the next step (petfinder api). This scenario results in a browser console error message of "too much recursion." We need to set up an on-page error message (must be a modal - we're not allowed to use alerts/confirms/prompts) telling the user to go back to the beginning and actually like some cat photos this time

**Comment by bferriman** [comment]
We could also modify the haveEnoughData function to check for the case that our catLibrary is empty (we're removing each photo from it as we show it, correct?) and return true (i.e. proceed to doing a cat search).  Then the cat search function would need to be able to handle cases where we have less than 2 likes for some/all attributes.
